name: flutter_notes_app
description: A simple notes app for practising/showcasing purposes.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.5
  flutter_bloc: 8.1.1
  isar: 2.5.0
  isar_flutter_libs: 2.5.0
  equatable: ^2.0.5
  path_provider: ^2.0.11
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.2.0
  flutter_lints: 2.0.1
  isar_generator: 2.5.0

flutter:
  uses-material-design: true